name: Bug Report
description: Report a bug in the Factorio Mocks Ecosystem
title: "[BUG] "
labels: ["type: bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have read the documentation and this appears to be a bug
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the ecosystem is affected?
      options:
        - factorio-mocks (this repository)
        - factorio-mocks-generator
        - factorio-mocks-modpacks
        - factorio-mocks-data
        - factorio-mocks-loader
        - Documentation
        - CI/CD Workflows
        - Not sure
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened, including any error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide relevant environment details
      placeholder: |
        - OS: [e.g., Windows 11, Ubuntu 24.04]
        - Factorio Version: [e.g., 2.0.15]
        - Mod Versions: [if applicable]
        - Lua Version: [if applicable]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Paste any relevant logs, error messages, or screenshots
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
