blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussion
    url: https://github.com/QuingKhaos/factorio-mocks/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 📖 Documentation
    url: https://github.com/QuingKhaos/factorio-mocks/tree/main/planning
    about: Browse the project planning and architecture documentation
  - name: ☕ Support the Project
    url: https://ko-fi.com/quingkhaos
    about: Support ongoing development with a coffee contribution