name: Feature Request
description: Suggest a new feature or enhancement for the Factorio Mocks Ecosystem
title: "[FEATURE] "
labels: ["type: feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have reviewed the project roadmap and this feature isn't already planned
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the ecosystem would this feature affect?
      options:
        - factorio-mocks (this repository)
        - factorio-mocks-generator
        - factorio-mocks-modpacks
        - factorio-mocks-data
        - factorio-mocks-loader
        - Planning
        - CI/CD Workflows
        - Cross-component/Architecture
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/Blocking
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there alternative approaches you've considered?
      placeholder: Describe any alternative solutions or workarounds you've considered

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: How would this feature be used? Provide specific examples
      placeholder: |
        Example use cases:
        1. As a mod developer, I want to...
        2. When testing my mod, I need to...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How would we know this feature is successfully implemented?
      placeholder: |
        This feature would be complete when:
        - [ ] Criterion 1
        - [ ] Criterion 2

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be interested in helping implement this feature
        - label: I could help with testing this feature
        - label: I could help with documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references that would be helpful
